package gui;

import java.awt.*;  
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;
import mainCode.Game;
import java.util.Observer;
import java.util.Observable;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Creating YouWin page
 * @author Ahmet Kaan Uguralp
 * @version 12.05.2019
 */
public class YouWinPage extends javax.swing.JPanel implements Observer {
   
   /**
    * Creates new form YouWinPage
    */
   //properties
   JTextField congText;
   JButton exitButton;
   JLabel imgLabel;
   JTextField moneyField;
   JTextField refText;
   Game game;
   
   //constructors
   public YouWinPage() {}
   
   public YouWinPage( Game game ) 
   {
       this.game = game;       
       game.addObserver( this );
       
       initComponents();
       handleActionListeners();        
    }
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   // create the components of you win page
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
      private void initComponents() {

        moneyField = new JTextField();
        exitButton = new JButton();
        refText = new JTextField();
        congText = new JTextField();

        setBackground(new Color(153, 255, 153));

        moneyField.setEditable(false);
        moneyField.setFont(new Font("Gisha", 0, 48)); // NOI18N
        moneyField.setForeground(new Color(51, 204, 51));
        moneyField.setHorizontalAlignment(JTextField.CENTER);
        moneyField.setText("$WIN");
        moneyField.setBorder(null);
        moneyField.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        moneyField.addInputMethodListener(new InputMethodListener() {
            public void caretPositionChanged(InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(InputMethodEvent evt) {
                moneyFieldInputMethodTextChanged(evt);
            }
        });

        exitButton.setFont(new Font("Gisha", 0, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setCursor(new Cursor(Cursor.HAND_CURSOR));;

        refText.setEditable(false);
        refText.setBackground(new Color(153, 255, 153));
        refText.setFont(new Font("Times New Roman", 1, 12)); // NOI18N
        refText.setHorizontalAlignment(JTextField.CENTER);
        refText.setText("You got real estate investment!");
        refText.setBorder(null);

        congText.setEditable(false);
        congText.setBackground(new Color(153, 255, 153));
        congText.setFont(new Font("Gisha", 1, 36)); // NOI18N
        congText.setForeground(new Color(204, 0, 204));
        congText.setHorizontalAlignment(JTextField.CENTER);
        congText.setText("CONGRATULATIONS!");
        congText.setBorder(null);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(congText, GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(refText, GroupLayout.PREFERRED_SIZE, 292, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(moneyField, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(exitButton, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE )
                .addComponent(congText, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap( LayoutStyle.ComponentPlacement.UNRELATED )
                .addComponent(moneyField, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(exitButton, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>         
   
   private void moneyFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                  
      // TODO add your handling code here:
   }                                                 
   
   // adding action listener
   public void handleActionListeners()
   {
      exitButton.addActionListener( new ActionListener() { 
         @Override
         public void actionPerformed( ActionEvent evt )
         {
            game.lastStage();
         }
      } );
   }
   
   // update method
   public void update( Observable obs, Object obj )
   {
      if ( game.getStage().equals( "you win" ) )
      {
         moneyField.setText( "+ " + game.getCurrentLocation().getTax() );
      }
      
      setVisible( game.getStage().equals( "you win" ) );
   }                 
}
